In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("nyc_weather.csv")

In [9]:
df.head(6)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259

In [17]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [18]:
df.tail()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [20]:
df.shape

(31, 11)

In [22]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [23]:
df.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   EST                   31 non-null     object
 1   Temperature           31 non-null     int64
 2   DewPoint              31 non-null     int64
 3   Humidity              31 non-null     int64
 4   Sea Level PressureIn  31 non-null     float64
 5   VisibilityMiles       31 non-null     int64
 6   WindSpeedMPH          28 non-null     float64
 7   PrecipitationIn       31 non-null     object
 8   CloudCover            31 non-null     int64
 9   Events                9 non-null      object
 10  WindDirDegrees        31 non-null     int64
dtypes: float64(2), int64(6), object(3)
memory usage: 2.8+ KB

In [25]:
df.describe()

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,CloudCover,WindDirDegrees
count,31.000000,31.000000,31.000000,31.000000,31.000000,28.000000,31.000000,31.000000
mean,34.677419,17.838710,51.677419,29.992903,9.193548,6.892857,3.129032,247.129032
std,7.639315,11.378626,11.634395,0.237237,1.939405,2.871821,2.629853,92.308086
min,20.000000,-3.000000,33.000000,29.520000,1.000000,2.000000,0.000000,34.000000
25%,29.000000,10.000000,44.500000,29.855000,9.000000,5.000000,1.000000,238.000000
50%,35.000000,18.000000,50.000000,30.010000,10.000000,6.500000,3.000000,281.000000
75%,39.500000,23.000000,55.000000,30.140000,10.000000,8.000000,4.500000,300.000000
max,50.000000,46.000000,78.000000,30.570000,10.000000,16.000000,8.000000,345.000000

In [27]:
df['Events']

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
5          NaN
6          NaN
7          NaN
8         Rain
9         Rain
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15        Rain
16    Fog-Snow
17        Snow
18         NaN
19         NaN
20         NaN
21        Snow
22    Fog-Snow
23        Snow
24         NaN
25         NaN
26        Rain
27         NaN
28         NaN
29         NaN
30         NaN
Name: Events, dtype: object

In [30]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [33]:
df[['Temperature','WindSpeedMPH']]

    Temperature  WindSpeedMPH
0            38           8.0
1            36           7.0
2            40           8.0
3            25           9.0
4            20           5.0
5            33           4.0
6            39           2.0
7            39           4.0
8            44           8.0
9            50           NaN
10           33           NaN
11           35           6.0
12           26          10.0
13           30           5.0
14           43           5.0
15           47           7.0
16           36           6.0
17           25          12.0
18           22          11.0
19           32           6.0
20           31           6.0
21           26           NaN
22           26          16.0
23           28           6.0
24           34           3.0
25           43           7.0
26           41           7.0
27           37           5.0
28           36           8.0
29           34           7.0
30           46           5.0

In [36]:
df.iloc[2]

EST                     1/3/2016
Temperature                   40
DewPoint                      21
Humidity                      47
Sea Level PressureIn       29.86
VisibilityMiles               10
WindSpeedMPH                 8.0
PrecipitationIn                0
CloudCover                     1
Events                       NaN
WindDirDegrees               277
Name: 2, dtype: object

In [35]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [37]:
df.iloc[6]

EST                     1/7/2016
Temperature                   39
DewPoint                      11
Humidity                      33
Sea Level PressureIn       30.28
VisibilityMiles               10
WindSpeedMPH                 2.0
PrecipitationIn                0
CloudCover                     3
Events                       NaN
WindDirDegrees               293
Name: 6, dtype: object

In [38]:
df.loc[1]

EST                     1/2/2016
Temperature                   36
DewPoint                      18
Humidity                      46
Sea Level PressureIn       30.02
VisibilityMiles               10
WindSpeedMPH                 7.0
PrecipitationIn                0
CloudCover                     3
Events                       NaN
WindDirDegrees               275
Name: 1, dtype: object

In [41]:
df.iloc[1,8]

3

In [44]:
df.loc[1,8]

KeyError: 8

In [47]:
df.loc[1,'Events']

nan

In [54]:
df[df["Events"] == "Rain"]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311

In [55]:
df[df["Events"] == "Fog-Snow"]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42

In [57]:
df[df["Temperature"] > 30]

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [58]:
df['Temperature'].max()

50

In [59]:
df['Humidity'].min()

33

In [60]:
df['EST'][df['Events'] == 'Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object