## ****Filtering****

In [1]:
import pandas as pd

In [7]:
Olympics_bio = pd.read_excel("Olympics-Datas.xlsx",sheet_name = 'bios')

In [8]:
Olympics_bio.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [9]:
Olympics_result = pd.read_excel("Olympics-Datas.xlsx",sheet_name = 'result')

In [11]:
Olympics_result.tail()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
94,1900.0,Summer,Tennis,"Doubles, Men (Olympic)",Paul Lebreton,24,FRA,Paul Lecaron,5.0,True,NaN
95,1900.0,Summer,Tennis,"Singles, Handicap, Men (Olympic (non-medal))",Paul Lebreton,24,FRA,NaN,9.0,True,NaN
96,1900.0,Summer,Tennis,"Doubles, Handicap, Men (Olympic (non-medal))",Paul Lebreton,24,FRA,Paul Lecaron,3.0,True,NaN
97,1900.0,Summer,Tennis,"Singles, Men (Olympic)",Paul Lecaron,25,FRA,NaN,5.0,True,NaN
98,1900.0,Summer,Tennis,"Doubles, Men (Olympic)",Paul Lecaron,25,FRA,Paul Lebreton,5.0,True,NaN

In [12]:
Olympics_bio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   athlete_id    100 non-null    int64
 1   name          100 non-null    object
 2   born_date     96 non-null     object
 3   born_city     94 non-null     object
 4   born_region   94 non-null     object
 5   born_country  94 non-null     object
 6   NOC           100 non-null    object
 7   height_cm     43 non-null     float64
 8   weight_kg     42 non-null     float64
 9   died_date     56 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 7.9+ KB

In [14]:
Olympics_bio.describe()

       athlete_id   height_cm  weight_kg
count  100.000000   43.000000  42.000000
mean    50.500000  177.325581  70.476190
std     29.011492    7.984273   7.727802
min      1.000000  157.000000  55.000000
25%     25.750000  173.000000  64.000000
50%     50.500000  177.000000  70.000000
75%     75.250000  183.000000  76.000000
max    100.000000  191.000000  87.000000

In [19]:
Olympics_bio.loc[Olympics_bio['height_cm'] > 170, ['name', 'height_cm']]

                    name  height_cm
1         Arnaud Boetsch      183.0
2           Jean Borotra      183.0
5      Nicolas Chatelain      181.0
6          Patrick Chila      180.0
16            Guy Forget      189.0
17  Jean-Philippe Gatien      178.0
25         Henri Leconte      184.0
26     Christophe Legoût      177.0
31       Guillaume Raoux      180.0
32      Stéphane Renault      180.0
34       Fabrice Santoro      177.0
35       Étienne Thobois      186.0
40        Julie Bradbury      175.0
41         Gillian Clark      176.0
47            Sara Gomer      190.0
48         Alison Gordon      175.0
54         Monique Javer      177.0
55            Valda Lake      173.0
60          Kelly Morgan      178.0
68             Sam Smith      175.0
69           Helen Troke      172.0
71            Clare Wood      175.0
72   Joanne Wright-Goode      171.0
73            Sky Andrew      185.0
74          Simon Archer      189.0
76          Jeremy Bates      180.0
79            Neil Broad      191.0
81         Andrew Castle      190.0
83           Xinhua Chen      175.0
87        Laurie Doherty      178.0
89       Desmond Douglas      175.0
92           Anne Gibson      173.0
95            Andy Goode      183.0
97           Darren Hall      183.0
98            Tim Henman      185.0

In [20]:
Olympics_bio.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [23]:
Olympics_bio.iloc[[5,2]]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

In [29]:
Olympics_bio.loc[10:13,["name"]]

                       name
10  Élie, Comte de Lastours
11              Max Decugis
12                J. Defert
13           Étienne Durand

In [32]:
Olympics_bio.loc[Olympics_bio['weight_kg'] >78,['athlete_id','name','weight_kg']]

    athlete_id          name  weight_kg
16          17    Guy Forget       79.0
47          48    Sara Gomer       85.0
74          75  Simon Archer       86.0
79          80    Neil Broad       87.0
95          96    Andy Goode       83.0

In [33]:
Olympics_bio.loc[0:3, Olympics_bio['weight_kg']]

KeyError: "None of [Index([ nan, 76.0, 76.0, 64.0,  nan, 70.0, 73.0,  nan,  nan,  nan,  nan,  nan,\n        nan,  nan, 58.0,  nan, 79.0, 73.0,  nan,  nan,  nan,  nan,  nan,  nan,\n        nan, 78.0, 75.0,  nan,  nan,  nan,  nan, 77.0, 72.0,  nan, 68.0, 78.0,\n        nan,  nan,  nan,  nan, 64.0, 68.0,  nan,  nan,  nan,  nan,  nan, 85.0,\n       68.0, 55.0,  nan,  nan,  nan, 64.0, 64.0, 61.0,  nan, 63.0,  nan,  nan,\n       65.0,  nan, 59.0,  nan,  nan, 68.0,  nan,  nan, 62.0, 63.0,  nan, 65.0,\n       68.0, 78.0, 86.0,  nan, 72.0,  nan,  nan, 87.0,  nan, 74.0,  nan, 71.0,\n       64.0,  nan,  nan,  nan,  nan, 66.0,  nan,  nan, 70.0,  nan,  nan, 83.0,\n        nan, 73.0, 77.0,  nan],\n      dtype='float64')] are in the [columns]"

In [34]:
Olympics_bio.loc[0:3,['weight_kg']]

   weight_kg
0        NaN
1       76.0
2       76.0
3       64.0

In [37]:
Olympics_bio.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [49]:
Olympics_bio.loc[(Olympics_bio['height_cm']>170) & (Olympics_bio['born_country']== 'FRA'),['athlete_id','name','height_cm','NOC']]

    athlete_id                  name  height_cm     NOC
1            2        Arnaud Boetsch      183.0  France
2            3          Jean Borotra      183.0  France
5            6     Nicolas Chatelain      181.0  France
6            7         Patrick Chila      180.0  France
17          18  Jean-Philippe Gatien      178.0  France
25          26         Henri Leconte      184.0  France
26          27     Christophe Legoût      177.0  France
31          32       Guillaume Raoux      180.0  France
32          33      Stéphane Renault      180.0  France
35          36       Étienne Thobois      186.0  France

In [52]:
Olympics_bio[Olympics_bio['NOC'].str.contains('France')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
14,15,Damien Éloi,1969-07-04,Vire,Calvados,FRA,France,165.0,58.0,NaN
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
18,19,Maurice Germot,1882-11-15,Vichy,Allier,FRA,France,NaN,NaN,1958-08-06
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19
21,22,René Lacoste,1904-07-02,Paris Xe,Paris,FRA,France,NaN,NaN,1996-10-12
22,23,Daniel Lawton,1881-11-27,Cantenac,Gironde,FRA,France,NaN,NaN,1979-03-27
23,24,Paul Lebreton,1875-10-19,Paris IIe,Paris,FRA,France,NaN,NaN,1960-03-31
24,25,Paul Lecaron,1863-07-29,Neuilly-sur-Seine,Hauts-de-Seine,FRA,France,NaN,NaN,1940-09-17
25,26,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,NaN
26,27,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,NaN
27,28,"Guy, Baron Lejeune",NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
28,29,Albert Lippmann,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
29,30,Édouard Mény de Marangue,1882-11-30,Paris VIe,Paris,FRA,France,NaN,NaN,1960-01-23
30,31,André Prévost,1875-02-28,Paris VIIIe,Paris,FRA,France,NaN,NaN,1951-11-22
31,32,Guillaume Raoux,1970-02-14,Bagnols-sur-Cèze,Gard,FRA,France,180.0,77.0,NaN
32,33,Stéphane Renault,1968-03-01,Barfleur,Manche,FRA,France,180.0,72.0,NaN
33,34,Jean-Pierre Samazeuilh,1891-01-17,Bordeaux,Gironde,FRA,France,NaN,NaN,1965-04-13
34,35,Fabrice Santoro,1972-12-09,Tahiti,Îles du Vent,FPN,France,177.0,68.0,NaN
35,36,Étienne Thobois,1967-09-20,Amiens,Somme,FRA,France,186.0,78.0,NaN
36,37,Pierre Verdé-Delisle,1877-05-16,Trie-la-Ville,Oise,FRA,France,NaN,NaN,1960-07-18

In [54]:
Olympics_bio[Olympics_bio['NOC'].str.contains('france', case= False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
14,15,Damien Éloi,1969-07-04,Vire,Calvados,FRA,France,165.0,58.0,NaN
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
18,19,Maurice Germot,1882-11-15,Vichy,Allier,FRA,France,NaN,NaN,1958-08-06
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19
21,22,René Lacoste,1904-07-02,Paris Xe,Paris,FRA,France,NaN,NaN,1996-10-12
22,23,Daniel Lawton,1881-11-27,Cantenac,Gironde,FRA,France,NaN,NaN,1979-03-27
23,24,Paul Lebreton,1875-10-19,Paris IIe,Paris,FRA,France,NaN,NaN,1960-03-31
24,25,Paul Lecaron,1863-07-29,Neuilly-sur-Seine,Hauts-de-Seine,FRA,France,NaN,NaN,1940-09-17
25,26,Henri Leconte,1963-07-04,Lillers,Pas-de-Calais,FRA,France,184.0,78.0,NaN
26,27,Christophe Legoût,1973-08-06,Montbéliard,Doubs,FRA,France,177.0,75.0,NaN
27,28,"Guy, Baron Lejeune",NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
28,29,Albert Lippmann,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
29,30,Édouard Mény de Marangue,1882-11-30,Paris VIe,Paris,FRA,France,NaN,NaN,1960-01-23
30,31,André Prévost,1875-02-28,Paris VIIIe,Paris,FRA,France,NaN,NaN,1951-11-22
31,32,Guillaume Raoux,1970-02-14,Bagnols-sur-Cèze,Gard,FRA,France,180.0,77.0,NaN
32,33,Stéphane Renault,1968-03-01,Barfleur,Manche,FRA,France,180.0,72.0,NaN
33,34,Jean-Pierre Samazeuilh,1891-01-17,Bordeaux,Gironde,FRA,France,NaN,NaN,1965-04-13
34,35,Fabrice Santoro,1972-12-09,Tahiti,Îles du Vent,FPN,France,177.0,68.0,NaN
35,36,Étienne Thobois,1967-09-20,Amiens,Somme,FRA,France,186.0,78.0,NaN
36,37,Pierre Verdé-Delisle,1877-05-16,Trie-la-Ville,Oise,FRA,France,NaN,NaN,1960-07-18

In [62]:
Olympics_bio[Olympics_bio['born_region'].isin(['Paris'])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19
21,22,René Lacoste,1904-07-02,Paris Xe,Paris,FRA,France,NaN,NaN,1996-10-12
23,24,Paul Lebreton,1875-10-19,Paris IIe,Paris,FRA,France,NaN,NaN,1960-03-31
29,30,Édouard Mény de Marangue,1882-11-30,Paris VIe,Paris,FRA,France,NaN,NaN,1960-01-23
30,31,André Prévost,1875-02-28,Paris VIIIe,Paris,FRA,France,NaN,NaN,1951-11-22

In [66]:
Olympics_bio.query('born_city == "Paris VIIIe"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06
30,31,André Prévost,1875-02-28,Paris VIIIe,Paris,FRA,France,NaN,NaN,1951-11-22

In [68]:
Olympics_bio.query('born_region == "Paris" and height_cm > 150')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20

In [70]:
Olympics_bio.loc[0:3, ['name']]

                    name
0  Jean-François Blanchy
1         Arnaud Boetsch
2           Jean Borotra
3        Jacques Brugnon

In [76]:
Olympics_bio.loc[(Olympics_bio['weight_kg']>=64) & (Olympics_bio['born_region'] == 'Paris')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20

# **Adding/Removing Columns**

In [130]:
coffee = pd.read_csv("coffee.csv")

In [131]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [132]:
coffee_new = coffee.copy()

In [133]:
coffee_new["Price"] = 10

In [134]:
coffee.head(2)

      Day Coffee Type  Units Sold
0  Monday    Espresso          25
1  Monday       Latte          15

In [135]:
coffe_new.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25         10
1     Monday       Latte          15         15
2    Tuesday    Espresso          30         10
3    Tuesday       Latte          20         15
4  Wednesday    Espresso          35         10

In [136]:
import numpy as np

In [137]:
coffee_new["New_Price"] =np.where(coffee_new["Coffee Type"] == 'Espresso', 10,15)

In [139]:
coffee_new.head()

         Day Coffee Type  Units Sold  Price  New_Price
0     Monday    Espresso          25     10         10
1     Monday       Latte          15     10         15
2    Tuesday    Espresso          30     10         10
3    Tuesday       Latte          20     10         15
4  Wednesday    Espresso          35     10         10

In [140]:
coffee_new = coffee_new.drop(columns = ['Price'])

In [141]:
coffee_new.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25         10
1     Monday       Latte          15         15
2    Tuesday    Espresso          30         10
3    Tuesday       Latte          20         15
4  Wednesday    Espresso          35         10

In [143]:
coffee_new.head()

         Day Coffee Type  Units Sold  New_Price
0     Monday    Espresso          25         10
1     Monday       Latte          15         15
2    Tuesday    Espresso          30         10
3    Tuesday       Latte          20         15
4  Wednesday    Espresso          35         10

In [144]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [148]:
coffee_new['revenue'] = coffee_new['Units Sold'] * coffee_new['New_Price']

In [149]:
coffee_new.head()

         Day Coffee Type  Units Sold  New_Price  revenue
0     Monday    Espresso          25         10      250
1     Monday       Latte          15         15      225
2    Tuesday    Espresso          30         10      300
3    Tuesday       Latte          20         15      300
4  Wednesday    Espresso          35         10      350

In [151]:
coffee_new = coffee_new.rename(columns= {'New_Price':'Price'})

In [152]:
coffee_new

          Day Coffee Type  Units Sold  Price  revenue
0      Monday    Espresso          25     10      250
1      Monday       Latte          15     15      225
2     Tuesday    Espresso          30     10      300
3     Tuesday       Latte          20     15      300
4   Wednesday    Espresso          35     10      350
5   Wednesday       Latte          25     15      375
6    Thursday    Espresso          40     10      400
7    Thursday       Latte          30     15      450
8      Friday    Espresso          45     10      450
9      Friday       Latte          35     15      525
10   Saturday    Espresso          45     10      450
11   Saturday       Latte          35     15      525
12     Sunday    Espresso          45     10      450
13     Sunday       Latte          35     15      525

In [153]:
Oly_bio = Olympics_bio.copy()

In [160]:
Oly_bio.head(2)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN

In [167]:
 Oly_bio.loc[Oly_bio['name'] =='Arnaud Boetsch']

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN

In [186]:
Oly_bio['Name_1'] = Oly_bio['name'].str.split(' ').str[0]

In [187]:
Oly_bio.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Name_1
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [188]:
Oly_bio.query('Name_1 == "George"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Name_1
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21,George
99,100,George Hillyard,1864-02-06,Hanwell,England,GBR,Great Britain,NaN,NaN,1943-03-24,George

In [189]:
Oly_bio['born_datetime'] = pd.to_datetime(Oly_bio['born_date'])

In [191]:
Oly_bio['born_year'] = Oly_bio['born_datetime'].dt.year

In [192]:
Oly_bio[['name','born_year']]

                     name  born_year
0   Jean-François Blanchy     1886.0
1          Arnaud Boetsch     1969.0
2            Jean Borotra     1898.0
3         Jacques Brugnon     1895.0
4            Albert Canet     1878.0
..                    ...        ...
95             Andy Goode     1960.0
96  Arthur Wentworth Gore     1868.0
97            Darren Hall     1965.0
98             Tim Henman     1974.0
99        George Hillyard     1864.0

[100 rows x 2 columns]

In [197]:
Oly_bio['height_Cat'] = Oly_bio['height_cm'].apply(lambda x: 'Short' if x<180 else 'Tall')

In [198]:
Oly_bio

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Name_1,born_datetime,born_year,height_Cat
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Andy Goode,1960-01-30,Welwyn Garden City,England,GBR,Great Britain,183.0,83.0,NaN,Andy,1960-01-30,1960.0,Tall
96,97,Arthur Wentworth Gore,1868-01-02,Lyndhurst,England,GBR,Great Britain,NaN,NaN,1928-12-01,Arthur,1868-01-02,1868.0,Tall
97,98,Darren Hall,1965-10-25,Walthamstow,England,GBR,Great Britain,183.0,73.0,NaN,Darren,1965-10-25,1965.0,Tall
98,99,Tim Henman,1974-09-06,Oxford,England,GBR,Great Britain,185.0,77.0,NaN,Tim,1974-09-06,1974.0,Tall
99,100,George Hillyard,1864-02-06,Hanwell,England,GBR,Great Britain,NaN,NaN,1943-03-24,George,1864-02-06,1864.0,Tall

In [204]:
Oly_bio['height_Cat'] = Oly_bio['height_cm'].apply(lambda x: 'Short' if x<180 else ('Average' if x<185 else 'Tall'))

In [205]:
Oly_bio

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Name_1,born_datetime,born_year,height_Cat
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Andy Goode,1960-01-30,Welwyn Garden City,England,GBR,Great Britain,183.0,83.0,NaN,Andy,1960-01-30,1960.0,Average
96,97,Arthur Wentworth Gore,1868-01-02,Lyndhurst,England,GBR,Great Britain,NaN,NaN,1928-12-01,Arthur,1868-01-02,1868.0,Tall
97,98,Darren Hall,1965-10-25,Walthamstow,England,GBR,Great Britain,183.0,73.0,NaN,Darren,1965-10-25,1965.0,Average
98,99,Tim Henman,1974-09-06,Oxford,England,GBR,Great Britain,185.0,77.0,NaN,Tim,1974-09-06,1974.0,Tall
99,100,George Hillyard,1864-02-06,Hanwell,England,GBR,Great Britain,NaN,NaN,1943-03-24,George,1864-02-06,1864.0,Tall

In [213]:
def categories_athlete(row):
    if row['height_cm'] <175 and row['weight_kg'] < 70:
        return 'Light_weight'
    elif row['height_cm'] <185 or row['weight_kg'] < 80:
        return 'Middle_weight'
    else:
        return 'Heavy weight'

In [214]:
Oly_bio['Categories_athle'] = Oly_bio.apply(categories_athlete, axis =1)

In [215]:
Oly_bio

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,Name_1,born_datetime,born_year,height_Cat,Categories_athle
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,Average,Middle_weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,Average,Middle_weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,Short,Light_weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,Tall,Heavy weight
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Andy Goode,1960-01-30,Welwyn Garden City,England,GBR,Great Britain,183.0,83.0,NaN,Andy,1960-01-30,1960.0,Average,Middle_weight
96,97,Arthur Wentworth Gore,1868-01-02,Lyndhurst,England,GBR,Great Britain,NaN,NaN,1928-12-01,Arthur,1868-01-02,1868.0,Tall,Heavy weight
97,98,Darren Hall,1965-10-25,Walthamstow,England,GBR,Great Britain,183.0,73.0,NaN,Darren,1965-10-25,1965.0,Average,Middle_weight
98,99,Tim Henman,1974-09-06,Oxford,England,GBR,Great Britain,185.0,77.0,NaN,Tim,1974-09-06,1974.0,Tall,Middle_weight
99,100,George Hillyard,1864-02-06,Hanwell,England,GBR,Great Britain,NaN,NaN,1943-03-24,George,1864-02-06,1864.0,Tall,Heavy weight

In [216]:
nocs = pd.read_csv("noc_regions.csv")

In [222]:
nocs

     NOC       region                 notes
0    AFG  Afghanistan                   NaN
1    AHO      Curacao  Netherlands Antilles
2    ALB      Albania                   NaN
3    ALG      Algeria                   NaN
4    AND      Andorra                   NaN
..   ...          ...                   ...
225  YEM        Yemen                   NaN
226  YMD        Yemen           South Yemen
227  YUG       Serbia            Yugoslavia
228  ZAM       Zambia                   NaN
229  ZIM     Zimbabwe                   NaN

[230 rows x 3 columns]