**Adding columns**

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('nyc_weather.csv')

In [4]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [ ]:
df['TemperatureC']  ## add a value

KeyError: 'TemperatureC'

In [7]:
df['TemperatureC'] = (df['Temperature'] - 32) *5/9

In [10]:
df['TemperatureC'].head()

0   -15.925926
1   -16.543210
2   -15.308642
3   -19.938272
4   -21.481481
Name: TemperatureC, dtype: float64

In [12]:
df['Temperature'].head()

0    3.333333
1    2.222222
2    4.444444
3   -3.888889
4   -6.666667
Name: Temperature, dtype: float64

In [13]:
df = pd.read_csv("nyc_weather.csv")

In [14]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [15]:
df['TemperatureC'] = (df['Temperature'] - 32) *5/9

In [16]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,TemperatureC
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281,3.333333
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275,2.222222
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277,4.444444
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345,-3.888889
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333,-6.666667

In [17]:
df[['Temperature','TemperatureC']].head()

   Temperature  TemperatureC
0           38      3.333333
1           36      2.222222
2           40      4.444444
3           25     -3.888889
4           20     -6.666667

In [18]:
df['Others'] = None

In [19]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,TemperatureC,Others
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281,3.333333,None
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275,2.222222,None
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277,4.444444,None
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345,-3.888889,None
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333,-6.666667,None

**Removing columns**

In [20]:
df.drop("TemperatureC", axis=1)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,Others
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281,None
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275,None
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277,None
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345,None
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333,None
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259,None
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293,None
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79,None
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76,None
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109,None
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289,None
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235,None
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284,None
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266,None
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101,None
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340,None
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345,None
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293,None
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293,None
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302,None
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312,None
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34,None
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42,None
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327,None
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286,None
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244,None
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311,None
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234,None
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298,None
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257,None
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241,None

**Sorting**

In [23]:
df.sort_values('Temperature', ascending=False).head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees,TemperatureC,Others
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109,10.000000,None
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340,8.333333,None
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241,7.777778,None
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76,6.666667,None
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101,6.111111,None

**value_counts()**

In [26]:
df['Events'].value_counts()

Events
Rain        4
Snow        3
Fog-Snow    2
Name: count, dtype: int64

In [29]:
df["Events"].value_counts(dropna=False)

Events
NaN         22
Rain         4
Snow         3
Fog-Snow     2
Name: count, dtype: int64

**unique() , nunique()**

In [35]:
df['Events'].unique()

array([nan, 'Rain', 'Fog-Snow', 'Snow'], dtype=object)

In [36]:
df['Events'].nunique()

3